In [1]:
import numpy as np
from numpy import linalg
import scipy
import scipy.linalg as la
import scipy.optimize
import matplotlib.pyplot as plt
%matplotlib inline


## Задача 1.

Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$


#### Решение

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\
2 & 1 & -1 & 1\\
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\
-2\\
4
\end{matrix}
\end{pmatrix}->
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\
2 & 1 & -1 & 1\\
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\
-2\\
4
\end{matrix}
\end{pmatrix}->
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\
0 & -1 & 1 & 5\\
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\
-2\\
4
\end{matrix}
\end{pmatrix}$

Ответ:

$\begin{cases}
x_{3} = \frac{3}{2}x_{4} - 2\\
x_{2} = \frac{13}{2}x_{4}\\
x_{1} = -3x_{4} - 2
\end{cases}, x_{4} \in \mathbb{R}$

## Задача 2.

Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$


#### Решение

а)$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1 \\
2 & -5 & -3 \\
1 & 1 & -1 
\end{matrix}\right|
\begin{matrix}
4\\
-17\\
0
\end{matrix}
\end{pmatrix}->
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\
2 & -5 & -3 \\
0 & -4 & 4 
\end{matrix}\right|
\begin{matrix}
0\\
-17\\
4
\end{matrix}
\end{pmatrix}->
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\
0 & -7 & -1 \\
0 & 1 & -1 
\end{matrix}\right|
\begin{matrix}
0\\
-17\\
-1
\end{matrix}
\end{pmatrix}->
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\
0 & -7 & -1 \\
0 & 0 & -8 
\end{matrix}\right|
\begin{matrix}
0\\
-17\\
-24
\end{matrix}
\end{pmatrix}$

Ответ:

система совместна и будет иметь единственное решение.

б)$
\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\
1 & -2 & 3 \\
3 & -6 & 9 
\end{matrix}\right|
\begin{matrix}
1\\
-2\\
5
\end{matrix}
\end{pmatrix}->
\begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 3 \\
2 & -4 & 6 \\
3 & -6 & 9 
\end{matrix}\right|
\begin{matrix}
-2\\
1\\
5
\end{matrix}
\end{pmatrix}->
\begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 3 \\
0 & 0 & 0 \\
3 & -6 & 9 
\end{matrix}\right|
\begin{matrix}
-2\\
5\\
5
\end{matrix}
\end{pmatrix}$

Ответ:

система несовместна и не имеет решений.

в)$
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5\\
3 & 1 & -8 
\end{matrix}\right|
\begin{matrix}
4\\
-2
\end{matrix}
\end{pmatrix}->
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5\\
0 & -5 & -23 
\end{matrix}\right|
\begin{matrix}
4\\
-14
\end{matrix}
\end{pmatrix}$

Ответ:

система совместна и имеет бесконечное кол-во решений.

In [2]:
def sovmest(A, A_w):
    if linalg.matrix_rank(A) == linalg.matrix_rank(A_w):
        if linalg.matrix_rank(A) == A.shape[1]:
            print(f'Система совместна и имеет единственное решение')
        elif linalg.matrix_rank(A) < A.shape[1]:
            print(f'Система совместна и имеет бесконечное число решений') 
    elif linalg.matrix_rank(A) < linalg.matrix_rank(A_w):
        print(f'Система несовместна, решений нет')
        
A = np.array([[3, -1, 1],[2, -5, -3], [1, 1, -1]])
A_w = np.append(A, np.array([[4],[-17], [0]]), axis=1)
print("а")
sovmest(A, A_w)

A = np.array([[2, -4, 6],[1, -2, 3], [3, -6, 9]])
A_w = np.append(A, np.array([[1],[-2], [5]]), axis=1)
print("б")
sovmest(A, A_w)

A = np.array([[1, 2, 5],[3, 1, -8]])
A_w = np.append(A, np.array([[4],[-2]]), axis=1)
print("в")
sovmest(A, A_w)

а
Система совместна и имеет единственное решение
б
Система несовместна, решений нет
в
Система совместна и имеет бесконечное число решений


## Задача 3. 


Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

#### Решение

Ранг дополненной матрицы равен рангу основной и равен числу переменных, значит система совместна и имеет единственное решение.

In [3]:
A = np.array([[1, 3, -2, 4],[0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
A_w = np.append(A, np.array([[3],[2],[4],[1]]), axis=1)
sovmest(A, A_w)

Система совместна и имеет единственное решение


## Задача 4.

Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

#### Решение

$
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}->
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a
\end{matrix}
\end{pmatrix}->
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & 1 & 2\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
\frac{4a-b}{3}\\
c+a-2b
\end{matrix}
\end{pmatrix}$

Cистема будет совместной при c+a-2b=0. 

Во всех остальных случаях система будет несовместна.

## Задача 1.

Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

#### Решение

а)$A = 
\begin{vmatrix}
1 & -2\\
3 & -4
\end{vmatrix} = 2,$ $A_{1} = \begin{vmatrix}
1 & -2\\
7 & -4
\end{vmatrix} = 10,$ $A_{2} = \begin{vmatrix}
1 & 1\\
3 & 7
\end{vmatrix} = 4.$

$x_{1} = \frac{A_{1}}{A} = 5,$ 

$x_{2} = \frac{A_{2}}{A} = 2$


б)$A = \begin{vmatrix}
2 & -1 & 5\\
1 & 1 & -3\\
2 & 4 & 1
\end{vmatrix} = 2+20+6-10+24+1=43$, 
$A_{1} = \begin{vmatrix}
10 & -1 & 5\\
-2 & 1 & -3\\
1 & 4 & 1
\end{vmatrix} = 10-40+3-5+120-2=86$, 
$A_{2} = \begin{vmatrix}
2 & 10 & 5\\
1 & -2 & -3\\
2 & 1 & 1
\end{vmatrix} = -4+5-60+20+6-10=-43$, 
$A_{3} = \begin{vmatrix}
2 & -1 & 10\\
1 & 1 & -2\\
2 & 4 & 1
\end{vmatrix} = 2+40+4-20+16+1=43$,

$x_{1} = \frac{A_{1}}{A} = 2$,

$x_{2} = \frac{A_{2}}{A}=-1$,

$x_{3} = \frac{A_{3}}{A}=1$

In [4]:
A = np.array([[1, -2,],[3, -4]])
s = np.array([[1, 7]])
A_1 = np.copy(A)
A_1[::,0] = s
A_2 = np.copy(A)
A_2[::,1] = s
x1 = round(linalg.det(A_1)/linalg.det(A), 4)
x2 = round(linalg.det(A_2)/linalg.det(A), 4)
print(f'\nx1 = {x1}, \nx2 = {x2}')


x1 = 5.0, 
x2 = 2.0


In [5]:
A = np.array([[2, -1, 5],[1, 1, -3], [2, 4, 1]])
s = np.array([[10, -2, 1]])
A_1 = np.copy(A)
A_1[::,0] = s
A_2 = np.copy(A)
A_2[::,1] = s
A_3 = np.copy(A)
A_3[::,2] = s
x1 = round(linalg.det(A_1)/linalg.det(A), 4)
x2 = round(linalg.det(A_2)/linalg.det(A), 4)
x3 = round(linalg.det(A_3)/linalg.det(A), 4)
print(f'\nx1 = {x1}, \nx2 = {x2}, \nx3 = {x3}')


x1 = 2.0, 
x2 = -1.0, 
x3 = 1.0


## Задача 2.

Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    

#### Решение

а)$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}->
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}->
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$ 

Получаем L-матрицу: 

$
\begin{pmatrix}
1 & 0 & 0\\
2 & 1 & 0\\
3 & 4 & 1
\end{pmatrix}$


б)$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}->
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}->
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}->
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$

Получаем L-матрицу:

$
\begin{pmatrix}
1 & 0 & 0 & 0\\
2 & 1 & 0 & 0\\
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$

## Задача 3.

Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

#### Решение


$\begin{pmatrix}
2 & 1 & 3\\
11 & 7 & 5\\
9 & 8 & 4
\end{pmatrix}->
\begin{pmatrix}
2 & 1 & 3\\
0 & 1.5 & -11.5\\
0 & 3.5 & -9.5
\end{pmatrix}->
\begin{pmatrix}
2 & 1 & 3\\
0 & 1.5 & -11.5\\
0 & 0 & \frac{52}{3}
\end{pmatrix}$

L-матрица:

$\begin{pmatrix}
1 & 0 & 0\\
5.5 & 1 & 0\\
4.5 & \frac{7}{3} & 1
\end{pmatrix}$

Решим систему Ly=b:

$\begin{cases}
y_{1} = 1\\
5.5y_{1} + y_{2} = -6\\
4.5y_{1} + \frac{7}{3}y_{2} + y_{3} = -5
\end{cases}=>\begin{cases}
y_{1} = 1\\
y_{2} = -11.5\\
y_{3} = \frac{52}{3}
\end{cases}$

Решение системы:

$\begin{cases}
2x_{1} + x_{2} + 3x_{3} = 1\\
1.5x_{2} -11.5x_{3} = -11.5\\
\frac{52}{3}x_{3} = \frac{52}{3}
\end{cases}=>\begin{cases}
x_{3} = 1\\
x_{2} = 0\\
x_{1} = -1
\end{cases}$

In [6]:
A_3 = np.array([[2,1,3],[11,7,5],[9,8,4]])
b_3 = np.array([[1],[-6],[-5]])
np.linalg.solve(A_3,b_3)

array([[-1.],
       [ 0.],
       [ 1.]])

## Задача 4.

Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$


#### Решение

$l_{11} = \sqrt{81}=9\\
l_{21} = \frac{-45}{9}=-5\\
l_{31} = \frac{45}{9}=5\\
l_{22} = \sqrt{50-25}=5\\
l_{32} = \frac{-15-5\cdot (-5)}{5}=2\\
l_{33} = \sqrt{38-25-4}=3$

Матрицы разложения:

$L = \begin{pmatrix}
9 & 0 & 0\\
-5 & 5 & 0\\
5 & 2 & 3
\end{pmatrix}, \; \; L^{T} = \begin{pmatrix}
9 & -5 & 5\\
0 & 5 & 2\\
0 & 0 & 3
\end{pmatrix}$

Решим систему Ly=b:

$\begin{cases}
9y_{1}=531\\
-5y_{1}+5y_{2}=-460\\
5y_{1} + 2y_{2} + 3y_{3} = 193
\end{cases}=>\begin{cases}
y_{1}=59\\
y_{2}=-33\\
y_{3} = -12
\end{cases}$

Решим систему:

$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59\\
5x_{2}+2x_{3}=-33\\
3x_{3}=-12
\end{cases}=>\begin{cases}
x_{1}=6\\
x_{2}=-5\\
x_{3}=-4
\end{cases}$

In [7]:
A_4 = np.array([[81,-45,45],[-45,50,-15],[45,-15,38]])
b_4 = np.array([[531],[-460],[193]])
np.linalg.cholesky(A_4)

array([[ 9.,  0.,  0.],
       [-5.,  5.,  0.],
       [ 5.,  2.,  3.]])

In [8]:
np.linalg.solve(A_4,b_4)

array([[ 6.],
       [-5.],
       [-4.]])

## Задача 5.

Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

Возьмем в качестве исходных данных систему

$$\begin{cases}
3x_{1}+x_{2}-x_{3}=0, \\
2x_{1}+x_{2}-x_{3}=-2, \\
x_{1}+x_{2}-3x_{3}=4.
\end{cases}$$

In [9]:
A = np.array([[3., 1., -1.], [0., 0., -1.], [1., 1., -3.]])
b = np.array([0., -2., 4.])

def Gauss_solve(A, b):
    A_w = np.append(A, b[:,np.newaxis], axis=1)
    n = A_w.shape[0]
    x = np.zeros(n)
    for i in range(n):
        if A_w[i, i] ==0:
            s = np.copy(A_w[i, ::])
            A_w[i, ::] = A_w[i+1, ::]
            A_w[i+1, ::] = s
        A_w[i, ::] = A_w[i, ::]/A_w[i, i]
        for j in range(n):
            if j > i:
                A_w[j, ::] = A_w[j, ::] - A_w[i, ::]*A_w[j, i]
    print(A_w)
    
    for i in range(n-1, -1, -1):
        x[i] = A_w[i, n]
        for j in range(i+1, n):
            x[i] -= x[j]*A_w[i, j]
    print(x)

Gauss_solve(A, b)

[[ 1.          0.33333333 -0.33333333  0.        ]
 [ 0.          1.         -4.          6.        ]
 [-0.         -0.          1.          2.        ]]
[-4. 14.  2.]


In [10]:
linalg.solve(A, b)

array([-4., 14.,  2.])