In [1]:
import numpy as np

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

а)произведения неопределены<br>
б)AB - $2\times 3$, BA - неопределено<br>
в)AB - $8\times 8$, BA - $3\times 3$<br>
г)AB и BA - $4\times 4$

    
__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A + B = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

$A\times B = \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

$B\times A = \begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print("A+B\n",A+B)
print("A*B\n",np.dot(A,B))
print("B*A\n",np.dot(B,A))

A+B
 [[ 5 -3]
 [ 3  5]]
A*B
 [[  4 -11]
 [ 12  -3]]
B*A
 [[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A = \begin{pmatrix}
3 & 21\\
9 & -18
\end{pmatrix}$

$2B = \begin{pmatrix}
0 & 10\\
4 & -2
\end{pmatrix}$

$4C = \begin{pmatrix}
8 & -16\\
4 & 4
\end{pmatrix}$

$3A-2B+4C = \begin{pmatrix}
11 & -5\\
9 & -12
\end{pmatrix}$


In [3]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(3*A - 2*B + 4*C)

[[ 11  -5]
 [  9 -12]]


    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$AA^{T} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$

$A^{T}A = \begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$

In [4]:
A = np.array([[4, 1],
              [5, -2],
              [2,3]])
At = A.T
print("A*At \n",np.dot(A,At))
print("At*A\n",np.dot(At,A))

A*At 
 [[17 18 11]
 [18 29  4]
 [11  4 13]]
At*A
 [[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [5]:
def matrix_mult(A,B):  
    for row in A:
        assert len(B) == len(row)
    res = []
    for row in A:
        res_row = []
        for j, element in enumerate(row):
            for k in range(0,len(B[0])):
                try:
                    res_row[k] += element*B[j][k]
                except IndexError:
                    res_row.append(element*B[j][k])
        res.append(res_row)
    return res

In [6]:
A = [[1, 7], [3, -6]]
B = [[0, 5], [2, -1]]
C = matrix_mult(A,B)

An = np.array(A)
Bn = np.array(B)
Cn = An.dot(Bn)

print("Результат без NumPy\n",C)
print("Результат c NumPy\n",Cn)

Результат без NumPy
 [[14, -2], [-12, 21]]
Результат c NumPy
 [[ 14  -2]
 [-12  21]]


Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

a) sin*sin - (-cos)*cos = sin^2 + cos^2 = 1

б) матрица треугольная, определитель 4*5*9 = 180

в) 1*5*9 + 2*6*7 + 4*8*3 - 7*5*3 - 4*2*9 - 1*8*6 = 45+84+96 - 105-72-48= 225 - 225 = 0

In [7]:
x = 0

A = np.array([[np.sin(x), -np.cos(x)], [np.cos(x), np.sin(x)]])

B = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(np.linalg.det(A), np.linalg.det(B), np.linalg.det(C))

1.0 180.0 0.0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) 4*4 = 16

б) 4

в) 4*2 = 8


   
__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [8]:
A = np.array([[-2, 7, -3], 
             [4, -14, 6],
             [-3, 7, -13]])

np.linalg.det(A)

0.0

Определитель равен 0, значит матрица вырожденная.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

а) 3 строка - это сумма 1 и 2, убираем ее. Оставшиеся строки линейно не зависят друг от друга, значит ранг матрицы 2.

б) 3 строка - это сумма 1 и 2, убираем ее. Оставшиеся строки линейно не зависят друг от друга, значит ранг матрицы 3.