In [1]:
!pip install torch

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621


In [2]:
import torch
import numpy as np
from torch import nn 
from torch import optim
from torch.autograd import Variable

In [3]:
# Создайте случайный FloatTensor размера 3x4x5

In [4]:
a = torch.rand(3, 4, 5)
print(a)

tensor([[[0.7584, 0.1442, 0.5418, 0.7549, 0.4011],
         [0.9128, 0.4617, 0.5064, 0.4333, 0.2853],
         [0.3741, 0.3001, 0.7289, 0.3458, 0.6998],
         [0.9632, 0.6403, 0.2218, 0.3655, 0.9297]],

        [[0.0627, 0.0069, 0.7847, 0.9274, 0.6321],
         [0.6784, 0.0312, 0.3766, 0.3656, 0.4839],
         [0.2001, 0.5874, 0.5011, 0.7325, 0.8026],
         [0.7254, 0.6230, 0.5171, 0.4789, 0.1674]],

        [[0.2821, 0.8504, 0.5673, 0.0839, 0.1036],
         [0.4787, 0.9707, 0.0641, 0.8071, 0.3297],
         [0.7691, 0.8361, 0.8231, 0.2956, 0.8204],
         [0.2577, 0.1257, 0.5812, 0.3249, 0.2258]]])


In [5]:
# Выведите его форму (shape)

In [6]:
print(a.shape)

torch.Size([3, 4, 5])


In [7]:
# Приведите его к форме 6 X 10

In [8]:
b = a.reshape(6, 10)
print(b.shape)

torch.Size([6, 10])


In [9]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [10]:
a_new = a * torch.tensor([1, 4, 2, 2, 1])
print(a_new)

tensor([[[0.7584, 0.5767, 1.0835, 1.5099, 0.4011],
         [0.9128, 1.8470, 1.0127, 0.8666, 0.2853],
         [0.3741, 1.2003, 1.4578, 0.6915, 0.6998],
         [0.9632, 2.5611, 0.4437, 0.7310, 0.9297]],

        [[0.0627, 0.0274, 1.5693, 1.8548, 0.6321],
         [0.6784, 0.1249, 0.7531, 0.7312, 0.4839],
         [0.2001, 2.3495, 1.0022, 1.4650, 0.8026],
         [0.7254, 2.4920, 1.0342, 0.9579, 0.1674]],

        [[0.2821, 3.4016, 1.1345, 0.1677, 0.1036],
         [0.4787, 3.8829, 0.1283, 1.6141, 0.3297],
         [0.7691, 3.3443, 1.6462, 0.5911, 0.8204],
         [0.2577, 0.5026, 1.1624, 0.6498, 0.2258]]])


In [11]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [12]:
b_new = b[:, :6] * (b[:, :6])
print(b_new)
print(b_new.shape)

tensor([[5.7512e-01, 2.0784e-02, 2.9352e-01, 5.6994e-01, 1.6090e-01, 8.3316e-01],
        [1.3993e-01, 9.0050e-02, 5.3132e-01, 1.1955e-01, 4.8977e-01, 9.2779e-01],
        [3.9301e-03, 4.6985e-05, 6.1569e-01, 8.6005e-01, 3.9959e-01, 4.6019e-01],
        [4.0052e-02, 3.4501e-01, 2.5110e-01, 5.3653e-01, 6.4423e-01, 5.2617e-01],
        [7.9597e-02, 7.2318e-01, 3.2180e-01, 7.0336e-03, 1.0735e-02, 2.2919e-01],
        [5.9154e-01, 6.9902e-01, 6.7746e-01, 8.7361e-02, 6.7308e-01, 6.6435e-02]])
torch.Size([6, 6])


In [13]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [14]:
v = torch.tensor([1, 0.5, 2], requires_grad=True)
print(v.grad)
z = v ** 3 + v - 75 * v
print(z)
z.backward(v)
print(v.grad)

None
tensor([ -73.0000,  -36.8750, -140.0000], grad_fn=<SubBackward0>)
tensor([ -71.0000,  -36.6250, -124.0000])


In [15]:
# Создайте единичный тензор размера 5x6

In [16]:
t_one = torch.ones(5,6)
print(t_one)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [17]:
# Переведите его в формат numpy

In [18]:
t_np = t_one.numpy()
print(t_np)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [19]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

In [20]:
w1 = Variable(torch.Tensor([2,2]), requires_grad = True)
x = Variable(torch.Tensor([2,2]), requires_grad = False)
y = Variable(torch.Tensor([2,2]), requires_grad = False)

optimizer = torch.optim.SGD([w1], lr=0.0001)

criterion = torch.nn.MSELoss()

pred = x**w1 - 2 * x**2 + 5

optimizer.zero_grad()
loss = criterion(pred, y)
loss.backward()
optimizer.step()  
print(f'loss:\t {loss.item()}\n')
print(f'w1:\t {w1.data}')

loss:	 1.0

w1:	 tensor([2.0003, 2.0003])
